version: '3.8'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back-end/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=afonso
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=django_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  #front:
  #  build: ./frontend
  #  ports:
  #    - 8080:3000
  #  depends_on:
  #    - web
  sgbd:
    image: dpage/pgadmin4
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password123
volumes:
  postgres_data: