# Generated by Django 5.0.1 on 2024-01-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
